title: PARADISEC Workflows
description: PARADISEC technical workflows and archiving guides 
search_enabled: true
remote_theme: pmarsceill/just-the-docs
#color_scheme: light
# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
color_scheme: nil
search_enabled: true
search.previews: 3
search_tokenizer_separator: /[\s/]+/
heading_anchors: true

# Back to the top link
back_to_top: true
back_to_top_text: "Back to top"

callouts:
  note:
    title: Note
    color: blue
callouts level: loud

# callouts:
#   admonition:
#     # title:
#     color: grey-lt
#   attention:
#     title: Attention
#     color: purple
#   caution:
#     title: Caution
#     color: yellow
#   custom:
#     title: Custom
#     color: pink
#     opacity: 0.3
#   danger:
#     title: Danger
#     color: red
#   error:
#     title: Error
#     color: red
#   highlight:
#     color: yellow
#     opacity: 0.5
#   hint:
#     title: Hint
#     color: grey-dk
#   important:
#     title: Important
#     color: green
#   note:
#     title: Note
#     color: blue
#   tip:
#     title: Tip
#     color: grey-dk
#   warning:
#     title: Warning
#     color: red
    
#h1: {: .text-blue-000}
#color_scheme: "light"
#theme: "just-the-docs"


aux_links:
  "PARADISEC Workflows on GitHub":
    - "//github.com/paradisec-archive/PARADISEC_workflows"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true
