title: PARADISEC Workflows
description: PARADISEC technical workflows and archiving guides 
search_enabled: true
remote theme: jekyll-theme-slate
search_enabled: true
search.previews: 3
search_tokenizer_separator: /[\s/]+/
#heading_anchors: true
#color_scheme: "dark"

theme: jekyll-theme-slate

aux_links:
  "PARADISEC Workflows on GitHub":
    - "//github.com/paradisec-archive/PARADISEC_workflows"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true
