title: PARADISEC Workflows
description: PARADISEC technical workflows and archiving guides 
search_enabled: true
remote_theme: pmarsceill/just-the-docs
color_scheme: dark
search_enabled: true
search.previews: 3
search_tokenizer_separator: /[\s/]+/
heading_anchors: true
back_to_top: true
back_to_top_text: "Back to top"

#h1: {: .text-blue-000}
#color_scheme: "dark"
#theme: "just-the-docs"


aux_links:
  "PARADISEC Workflows on GitHub":
    - "//github.com/paradisec-archive/PARADISEC_workflows"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true